# Dialogue shown at minigame start and when the player clicks "No".
# Same format as events.toml: "Name: message" or "narrator: message"

[start_instructions]
dialogue = [
  "Kitty Marco: We've arrived.",
  "Kitty Marco: Let's release lanterns to light up the sky, this is our own lantern festival!",
  "narrator: Drag the lanterns to the where you want to release them, they'll fly upward from that spot."
]

[no_response]
dialogue = [
  "Kitty Marco: Sorry, this wasn't supposed to be here, let me get rid of that for you",
  "Kitty Marco: Now you can click the correct option!"
]
